### ISSUE TITLE
Developer Affiliations emails are wrong

### ISSUE THREAD

**Issue by jberkus** [cncf/gitdm.archive#462] opened 2020-09-15 16:00 UTC
Per troubleshooting with me, @jdumars, and @lukaszgryglicki:

Some bug in CNCF/gitdm is causing the developer affiliations generation to promiscuously grab email addresses which are not in any way associated with the contributor.  As a test case example:

```
hasbro17: geek.gsa!gmail.com, hasbro17!gmail.com, hasbro17!users.noreply.github.com, hello!zhaofeng.li, samuelcabralcruz!gmail.com
	Independent
```

Of the four real email addresses, only one belongs to the contributor Hasbro17 (Haseeb Tariq).  The other 3 belong to random other contributors to various cloud native projects (not even Kubernetes), such as Zhaofeng Li.  At an estimate, approximately 1/10 of all email addresses in developer_affiliations are incorrect in this way.

(Incidentally, Haseeb works for Red Hat)

**Comment by lukaszgryglicki** [comment] 2020-09-15 16:13
I would really like to help, but I have no way of determining if the contributor's email list is correct or not. I suggest creating PRs fixing this and I'll merge them and update data.

**Comment by jberkus** [comment] 2020-09-15 16:54
If you can confirm that the emails are used for no other purpose than the Kubernetes elections, then my suggestion is to simply remove them entirely.

**Comment by lukaszgryglicki** [comment] 2020-09-15 17:32
I'll keep them, some internal tools use them. People can always correct their emails in cncf/gitdm.

**Comment by jberkus** [comment] 2020-09-15 20:08
They can't, though, because there's no way to remove incorrect emails.

**Comment by jberkus** [comment] 2020-09-16 00:02
Regardless, there is no way for me to find all the incorrect emails.  And presumably gitdm is periodically used to pull new data, which would override any removals.  We really need to find the bug that's causing it to grab incorrect emails in the first place; I've dug into the code some but am having difficulty finding the code that actually pulls an email out of git.

Working hypothesis: an off-by-one error somewhere causing it to grab the email from the previous/next commit.

**Comment by lukaszgryglicki** [comment] 2020-09-16 04:16
```
They can't, though, because there's no way to remove incorrect emails.
```
They can - just create a PR against any *.txt file, removing emails in that PR.

**Comment by lukaszgryglicki** [comment] 2020-09-16 04:50
BTW, Josh, there is no periodic update of this repo. We only generate internal tasks with a list of users and their emails to research their affiliations (but those tasks don't add emails, they *use* emails to try to find affiliations). We don't use any automatic tools here, because their data is always lower quality than manual research (speaking about finding affiliations, not emails).

All changes to this gitdm data come this manual research (affiliation) and from users' PRs (which we treat as the highest priority - affiliation source is "user" then).

Then file from this repo [github_users.json](https://github.com/cncf/gitdm/blob/master/src/github_users.json) is imported as an affiliation source for all DevStats projects.

There are two places where users are connected with emails - one is this import and another one is GitHub API which is processed every sync (hourly).

Until yesterday we were not able to distinguish between them.

Yesterday I've added an `origin` column that specifies if a given email comes from `cncf/gitdm` JSON (origin = 0) or is coming from an actual commit (GH API) (origin = 1). So now we can return users with their *confirmed* emails - which means emails that were used to make at least one commit (but this is not the case for other contribution types like issues, comments, reviews, etc.). I've also set `origin=1` on all current emails that were used for any commit [here](https://github.com/cncf/devstats/blob/master/util_sql/modify_data_8.sql#L4).

The code is quite simple and I've double-checked it yesterday and I think there is no off-by-one bug there, listing this code for a reference (table name is `gha_actors_emails` you can search for it):

- GH API [code](https://github.com/cncf/devstatscode/blob/master/cmd/ghapi2db/ghapi2db.go#L305-L338) that adds emails from commit fields
- Import `cncf/gitdm` JSON code adding emails [here](https://github.com/cncf/devstatscode/blob/master/cmd/import_affs/import_affs.go#L707-L733), generating a list of emails per login [here](https://github.com/cncf/devstatscode/blob/master/cmd/import_affs/import_affs.go#L494-L503). It uses a map with a login key and a set of emails value (so I can't see any off-by-one problem).

Additionally, I've checked your example users and data in `gha_actors_emails` matches the `cncf/gitdm` JSON, so import. is OK, the data in JSON is incorrect, some part of this data is very old, so maybe there were some incorrect emails added in that old era when automatic tools were updating `cncf/gitdm` files instead of the manual process which is used more than 18 months already.

**Comment by lukaszgryglicki** [comment] 2020-09-16 04:50
cc @jberkus

**Comment by jberkus** [comment] 2020-09-16 18:58
So we discussed this in Kubernetes ContribEx.  Since we're planning to move away from email for elections by next year, we decided that the Kubernetes project doesn't care about this issue, and we won't be launching an outreach effort to get people to fix their own data.

Given this, it seems like the only thing to be done would be to warn folks about the issues in the Affiliates files themselves, so that future CNCF staff/volunteers don't use the email addresses for anything without verifying first.  Maybe just a line in the header?  If that works for you, I can draft something.

**Comment by lukaszgryglicki** [comment] 2020-09-16 19:03
Yes, that works for me.

**Comment by jberkus** [comment] 2020-09-16 23:42
Oh, BTW, if anyone ever tries to debug this in the future: 100% of the wrong emails seem to belong to contributors who are credited with either 4 or 5 email addresses.  We did not find any contributors credited with 2 or 3 addresses who had wrong emails (just out-of-date ones).  This is, however, an eyeball check, so it's not completely certain.

**Comment by lukaszgryglicki** [comment] 2020-09-24 05:52
Warning added, closing this, thanks for reporting!

**Closed as completed by lukaszgryglicki** 2020-09-24 05:52 UTC
